[Ready to be Merged] Create Physical Backed Token Module
lastrust/community-modules pull request #17
Opened 2023-01-26 12:00 UTC by darkty0x

2023-01-27 01:34 UTC, Top-Kraken requested changes
And there is no test scripts for the project. We need test scripts for the usage of PBT and PBTRandom.

2023-01-27 01:34 UTC, Top-Kraken commented on PhysicalBackedToken/contracts/interface/IBunzz.sol
> +interface IBunzz {
There is no usage of IBunzz interface. Please remove this.

2023-01-27 01:34 UTC, Top-Kraken commented on PhysicalBackedToken/package.json
> +    "@openzeppelin/contracts": "^4.8.0",
As you know, in Bunzz, we can only use 4.3.2 version for OpenZeppelin.

2023-02-02 17:26 UTC, solcmoon commented
> 

I agree.
@moco-bunzz you need to write test script.
Please check https://lastrust.notion.site/Checklist-for-coding-reviewing-phase-d8c89b8eee0f4656ba4719488d9fbbfa

2023-02-06 12:03 UTC, solcmoon approved these changes

2023-02-07 10:02 UTC, Top-Kraken approved these changes

2023-02-07 10:02 UTC, Top-Kraken approved these changes

2023-02-12 12:13 UTC, zkitty-norika commented
Hi @moco-bunzz, thank you for assigning me.
Priority-wise, preparing the audit report is not the first task according to the discussion with GK and Shota.
Now I'm focusing on the improvement of documentation and code quality.
I'd love to review from that point of view.

2024-08-26 15:36 UTC, closed without merging