[Ready to be Merged] Create Minimal Forwarder Module
lastrust/community-modules pull request #6
Opened 2022-12-20 19:50 UTC by darkty0x

2022-12-27 10:43 UTC, deep-quality-dev commented on minimal-forwarder/contracts/MinimalForwarder.sol
> +            assembly {
I suggest use `revert` instead of `invalid` in assembly, what do you think? @moco-bunzz

2022-12-27 10:49 UTC, deep-quality-dev commented on minimal-forwarder/contracts/MinimalForwarder.sol
> +            assembly {
Checked, the latest version of OZ is using assembly. that's fine, thanks

2022-12-27 10:49 UTC, deep-quality-dev approved these changes

2023-01-03 19:49 UTC, stefanandy commented
Hi @moco-bunzz  what usecase do you have in mind for this module?

2023-02-08 11:37 UTC, Top-Kraken requested changes

2024-08-26 15:36 UTC, closed without merging